export const genres = {
  count: 19,
  next: null,
  previous: null,
  results: [
    {
      id: 4,
      name: 'Action',
      slug: 'action',
      games_count: 174164,
      image_background:
        'https://media.rawg.io/media/games/490/49016e06ae2103881ff6373248843069.jpg',
      games: [
        {
          id: 3498,
          slug: 'grand-theft-auto-v',
          name: 'Grand Theft Auto V',
          added: 19981,
        },
        {
          id: 3328,
          slug: 'the-witcher-3-wild-hunt',
          name: 'The Witcher 3: Wild Hunt',
          added: 19254,
        },
        {
          id: 5286,
          slug: 'tomb-raider',
          name: 'Tomb Raider (2013)',
          added: 15801,
        },
        {
          id: 4291,
          slug: 'counter-strike-global-offensive',
          name: 'Counter-Strike: Global Offensive',
          added: 15802,
        },
        {
          id: 12020,
          slug: 'left-4-dead-2',
          name: 'Left 4 Dead 2',
          added: 15359,
        },
        {
          id: 5679,
          slug: 'the-elder-scrolls-v-skyrim',
          name: 'The Elder Scrolls V: Skyrim',
          added: 15103,
        },
      ],
    },
    {
      id: 51,
      name: 'Indie',
      slug: 'indie',
      games_count: 55187,
      image_background:
        'https://media.rawg.io/media/games/63f/63f0e68688cad279ed38cde931dbfcdb.jpg',
      games: [
        {
          id: 1030,
          slug: 'limbo',
          name: 'Limbo',
          added: 12839,
        },
        {
          id: 3272,
          slug: 'rocket-league',
          name: 'Rocket League',
          added: 11762,
        },
        {
          id: 422,
          slug: 'terraria',
          name: 'Terraria',
          added: 11736,
        },
        {
          id: 9767,
          slug: 'hollow-knight',
          name: 'Hollow Knight',
          added: 10182,
        },
        {
          id: 3612,
          slug: 'hotline-miami',
          name: 'Hotline Miami',
          added: 9857,
        },
        {
          id: 3790,
          slug: 'outlast',
          name: 'Outlast',
          added: 9788,
        },
      ],
    },
    {
      id: 3,
      name: 'Adventure',
      slug: 'adventure',
      games_count: 133888,
      image_background:
        'https://media.rawg.io/media/games/364/3642d850efb217c58feab80b8affaa89.jpg',
      games: [
        {
          id: 3498,
          slug: 'grand-theft-auto-v',
          name: 'Grand Theft Auto V',
          added: 19981,
        },
        {
          id: 3328,
          slug: 'the-witcher-3-wild-hunt',
          name: 'The Witcher 3: Wild Hunt',
          added: 19254,
        },
        {
          id: 5286,
          slug: 'tomb-raider',
          name: 'Tomb Raider (2013)',
          added: 15801,
        },
        {
          id: 13536,
          slug: 'portal',
          name: 'Portal',
          added: 15428,
        },
        {
          id: 28,
          slug: 'red-dead-redemption-2',
          name: 'Red Dead Redemption 2',
          added: 14572,
        },
        {
          id: 3439,
          slug: 'life-is-strange-episode-1-2',
          name: 'Life is Strange',
          added: 14393,
        },
      ],
    },
    {
      id: 5,
      name: 'RPG',
      slug: 'role-playing-games-rpg',
      games_count: 53161,
      image_background:
        'https://media.rawg.io/media/games/f99/f9979698c43fd84c3ab69280576dd3af.jpg',
      games: [
        {
          id: 3328,
          slug: 'the-witcher-3-wild-hunt',
          name: 'The Witcher 3: Wild Hunt',
          added: 19254,
        },
        {
          id: 5679,
          slug: 'the-elder-scrolls-v-skyrim',
          name: 'The Elder Scrolls V: Skyrim',
          added: 15103,
        },
        {
          id: 802,
          slug: 'borderlands-2',
          name: 'Borderlands 2',
          added: 14406,
        },
        {
          id: 58175,
          slug: 'god-of-war-2',
          name: 'God of War (2018)',
          added: 12777,
        },
        {
          id: 3070,
          slug: 'fallout-4',
          name: 'Fallout 4',
          added: 12743,
        },
        {
          id: 278,
          slug: 'horizon-zero-dawn',
          name: 'Horizon Zero Dawn',
          added: 12071,
        },
      ],
    },
    {
      id: 10,
      name: 'Strategy',
      slug: 'strategy',
      games_count: 53375,
      image_background:
        'https://media.rawg.io/media/games/e4a/e4ab7f784bdc38c76ce6e4cef9715d18.jpg',
      games: [
        {
          id: 13633,
          slug: 'civilization-v',
          name: "Sid Meier's Civilization V",
          added: 8890,
        },
        {
          id: 10243,
          slug: 'company-of-heroes-2',
          name: 'Company of Heroes 2',
          added: 8840,
        },
        {
          id: 13910,
          slug: 'xcom-enemy-unknown',
          name: 'XCOM: Enemy Unknown',
          added: 7872,
        },
        {
          id: 5525,
          slug: 'brutal-legend',
          name: 'Brutal Legend',
          added: 7807,
        },
        {
          id: 10065,
          slug: 'cities-skylines',
          name: 'Cities: Skylines',
          added: 7753,
        },
        {
          id: 11147,
          slug: 'ark-survival-of-the-fittest',
          name: 'ARK: Survival Of The Fittest',
          added: 7585,
        },
      ],
    },
    {
      id: 2,
      name: 'Shooter',
      slug: 'shooter',
      games_count: 59354,
      image_background:
        'https://media.rawg.io/media/games/e6d/e6de699bd788497f4b52e2f41f9698f2.jpg',
      games: [
        {
          id: 4200,
          slug: 'portal-2',
          name: 'Portal 2',
          added: 18155,
        },
        {
          id: 4291,
          slug: 'counter-strike-global-offensive',
          name: 'Counter-Strike: Global Offensive',
          added: 15802,
        },
        {
          id: 12020,
          slug: 'left-4-dead-2',
          name: 'Left 4 Dead 2',
          added: 15359,
        },
        {
          id: 4062,
          slug: 'bioshock-infinite',
          name: 'BioShock Infinite',
          added: 14567,
        },
        {
          id: 802,
          slug: 'borderlands-2',
          name: 'Borderlands 2',
          added: 14406,
        },
        {
          id: 13537,
          slug: 'half-life-2',
          name: 'Half-Life 2',
          added: 13726,
        },
      ],
    },
    {
      id: 40,
      name: 'Casual',
      slug: 'casual',
      games_count: 46417,
      image_background:
        'https://media.rawg.io/media/games/501/501e7019925a3c692bf1c8062f07abe6.jpg',
      games: [
        {
          id: 9721,
          slug: 'garrys-mod',
          name: "Garry's Mod",
          added: 9139,
        },
        {
          id: 326292,
          slug: 'fall-guys',
          name: 'Fall Guys: Ultimate Knockout',
          added: 8078,
        },
        {
          id: 9830,
          slug: 'brawlhalla',
          name: 'Brawlhalla',
          added: 7019,
        },
        {
          id: 356714,
          slug: 'among-us',
          name: 'Among Us',
          added: 6677,
        },
        {
          id: 1959,
          slug: 'goat-simulator',
          name: 'Goat Simulator',
          added: 5997,
        },
        {
          id: 16343,
          slug: 'a-story-about-my-uncle',
          name: 'A Story About My Uncle',
          added: 5626,
        },
      ],
    },
    {
      id: 14,
      name: 'Simulation',
      slug: 'simulation',
      games_count: 66491,
      image_background:
        'https://media.rawg.io/media/games/d1e/d1e70ce3762efcfc170c6bd067d7e9e3.jpg',
      games: [
        {
          id: 10035,
          slug: 'hitman',
          name: 'Hitman',
          added: 10073,
        },
        {
          id: 654,
          slug: 'stardew-valley',
          name: 'Stardew Valley',
          added: 9266,
        },
        {
          id: 9721,
          slug: 'garrys-mod',
          name: "Garry's Mod",
          added: 9139,
        },
        {
          id: 10243,
          slug: 'company-of-heroes-2',
          name: 'Company of Heroes 2',
          added: 8840,
        },
        {
          id: 9882,
          slug: 'dont-starve-together',
          name: "Don't Starve Together",
          added: 8593,
        },
        {
          id: 22509,
          slug: 'minecraft',
          name: 'Minecraft',
          added: 7909,
        },
      ],
    },
    {
      id: 7,
      name: 'Puzzle',
      slug: 'puzzle',
      games_count: 97150,
      image_background:
        'https://media.rawg.io/media/games/c00/c003705c0eaed100397ae408b7b89e90.jpg',
      games: [
        {
          id: 4200,
          slug: 'portal-2',
          name: 'Portal 2',
          added: 18155,
        },
        {
          id: 13536,
          slug: 'portal',
          name: 'Portal',
          added: 15428,
        },
        {
          id: 1030,
          slug: 'limbo',
          name: 'Limbo',
          added: 12839,
        },
        {
          id: 19709,
          slug: 'half-life-2-episode-two',
          name: 'Half-Life 2: Episode Two',
          added: 10247,
        },
        {
          id: 18080,
          slug: 'half-life',
          name: 'Half-Life',
          added: 9451,
        },
        {
          id: 1450,
          slug: 'inside',
          name: 'INSIDE',
          added: 7485,
        },
      ],
    },
    {
      id: 11,
      name: 'Arcade',
      slug: 'arcade',
      games_count: 22578,
      image_background:
        'https://media.rawg.io/media/games/7cf/7cf38d2d80267c121c6d0d361e9429ce.jpg',
      games: [
        {
          id: 3612,
          slug: 'hotline-miami',
          name: 'Hotline Miami',
          added: 9857,
        },
        {
          id: 17540,
          slug: 'injustice-gods-among-us-ultimate-edition',
          name: 'Injustice: Gods Among Us Ultimate Edition',
          added: 9002,
        },
        {
          id: 22509,
          slug: 'minecraft',
          name: 'Minecraft',
          added: 7909,
        },
        {
          id: 4003,
          slug: 'grid-2',
          name: 'GRID 2',
          added: 7100,
        },
        {
          id: 3408,
          slug: 'hotline-miami-2-wrong-number',
          name: 'Hotline Miami 2: Wrong Number',
          added: 5780,
        },
        {
          id: 16343,
          slug: 'a-story-about-my-uncle',
          name: 'A Story About My Uncle',
          added: 5626,
        },
      ],
    },
    {
      id: 83,
      name: 'Platformer',
      slug: 'platformer',
      games_count: 100648,
      image_background:
        'https://media.rawg.io/media/games/388/388935d851846f8ec747fffc7c765800.jpg',
      games: [
        {
          id: 1030,
          slug: 'limbo',
          name: 'Limbo',
          added: 12839,
        },
        {
          id: 422,
          slug: 'terraria',
          name: 'Terraria',
          added: 11736,
        },
        {
          id: 9767,
          slug: 'hollow-knight',
          name: 'Hollow Knight',
          added: 10182,
        },
        {
          id: 41,
          slug: 'little-nightmares',
          name: 'Little Nightmares',
          added: 10124,
        },
        {
          id: 18080,
          slug: 'half-life',
          name: 'Half-Life',
          added: 9451,
        },
        {
          id: 3144,
          slug: 'super-meat-boy',
          name: 'Super Meat Boy',
          added: 8943,
        },
      ],
    },
    {
      id: 59,
      name: 'Massively Multiplayer',
      slug: 'massively-multiplayer',
      games_count: 3323,
      image_background:
        'https://media.rawg.io/media/games/26b/26b27e1da9e3727fcb12e3e4e86c8c19.jpg',
      games: [
        {
          id: 32,
          slug: 'destiny-2',
          name: 'Destiny 2',
          added: 12860,
        },
        {
          id: 10213,
          slug: 'dota-2',
          name: 'Dota 2',
          added: 11649,
        },
        {
          id: 766,
          slug: 'warframe',
          name: 'Warframe',
          added: 11547,
        },
        {
          id: 290856,
          slug: 'apex-legends',
          name: 'Apex Legends',
          added: 10359,
        },
        {
          id: 10533,
          slug: 'path-of-exile',
          name: 'Path of Exile',
          added: 9301,
        },
        {
          id: 10142,
          slug: 'playerunknowns-battlegrounds',
          name: 'PlayerUnknown’s Battlegrounds',
          added: 9160,
        },
      ],
    },
    {
      id: 1,
      name: 'Racing',
      slug: 'racing',
      games_count: 24144,
      image_background:
        'https://media.rawg.io/media/games/367/367463d43c2a1465f27e830b5b1334ee.jpg',
      games: [
        {
          id: 3272,
          slug: 'rocket-league',
          name: 'Rocket League',
          added: 11762,
        },
        {
          id: 4003,
          slug: 'grid-2',
          name: 'GRID 2',
          added: 7100,
        },
        {
          id: 2572,
          slug: 'dirt-rally',
          name: 'DiRT Rally',
          added: 6384,
        },
        {
          id: 58753,
          slug: 'forza-horizon-4',
          name: 'Forza Horizon 4',
          added: 5726,
        },
        {
          id: 5578,
          slug: 'grid',
          name: 'Race Driver: Grid',
          added: 5179,
        },
        {
          id: 19491,
          slug: 'burnout-paradise-the-ultimate-box',
          name: 'Burnout Paradise: The Ultimate Box',
          added: 4476,
        },
      ],
    },
    {
      id: 15,
      name: 'Sports',
      slug: 'sports',
      games_count: 20744,
      image_background:
        'https://media.rawg.io/media/screenshots/f5a/f5abab52c4d606551cd5ec3ab709e501.jpg',
      games: [
        {
          id: 3272,
          slug: 'rocket-league',
          name: 'Rocket League',
          added: 11762,
        },
        {
          id: 326292,
          slug: 'fall-guys',
          name: 'Fall Guys: Ultimate Knockout',
          added: 8078,
        },
        {
          id: 2572,
          slug: 'dirt-rally',
          name: 'DiRT Rally',
          added: 6384,
        },
        {
          id: 53341,
          slug: 'jet-set-radio-2012',
          name: 'Jet Set Radio',
          added: 4911,
        },
        {
          id: 9575,
          slug: 'vrchat',
          name: 'VRChat',
          added: 4273,
        },
        {
          id: 622492,
          slug: 'forza-horizon-5',
          name: 'Forza Horizon 5',
          added: 4221,
        },
      ],
    },
    {
      id: 6,
      name: 'Fighting',
      slug: 'fighting',
      games_count: 11706,
      image_background:
        'https://media.rawg.io/media/games/234/23410661770ae13eac11066980834367.jpg',
      games: [
        {
          id: 17540,
          slug: 'injustice-gods-among-us-ultimate-edition',
          name: 'Injustice: Gods Among Us Ultimate Edition',
          added: 9002,
        },
        {
          id: 108,
          slug: 'mortal-kombat-x',
          name: 'Mortal Kombat X',
          added: 8297,
        },
        {
          id: 28179,
          slug: 'sega-mega-drive-and-genesis-classics',
          name: 'SEGA Mega Drive and Genesis Classics',
          added: 7645,
        },
        {
          id: 9830,
          slug: 'brawlhalla',
          name: 'Brawlhalla',
          added: 7019,
        },
        {
          id: 274480,
          slug: 'mortal-kombat-11',
          name: 'Mortal Kombat 11',
          added: 5032,
        },
        {
          id: 44525,
          slug: 'yakuza-kiwami',
          name: 'Yakuza Kiwami',
          added: 4261,
        },
      ],
    },
    {
      id: 19,
      name: 'Family',
      slug: 'family',
      games_count: 5390,
      image_background:
        'https://media.rawg.io/media/games/89a/89a700d3c6a76bd0610ca89ccd20da54.jpg',
      games: [
        {
          id: 3254,
          slug: 'journey',
          name: 'Journey',
          added: 8044,
        },
        {
          id: 2597,
          slug: 'lego-lord-of-the-rings',
          name: 'LEGO The Lord of the Rings',
          added: 5204,
        },
        {
          id: 3350,
          slug: 'broken-age',
          name: 'Broken Age',
          added: 4808,
        },
        {
          id: 3729,
          slug: 'lego-the-hobbit',
          name: 'LEGO The Hobbit',
          added: 4775,
        },
        {
          id: 1259,
          slug: 'machinarium',
          name: 'Machinarium',
          added: 4298,
        },
        {
          id: 1140,
          slug: 'world-of-goo',
          name: 'World of Goo',
          added: 4222,
        },
      ],
    },
    {
      id: 28,
      name: 'Board Games',
      slug: 'board-games',
      games_count: 8328,
      image_background:
        'https://media.rawg.io/media/screenshots/60e/60ef1b1853c35da13bc2ca9cbd1c0539.jpeg',
      games: [
        {
          id: 23557,
          slug: 'gwent-the-witcher-card-game',
          name: 'Gwent: The Witcher Card Game',
          added: 4496,
        },
        {
          id: 327999,
          slug: 'dota-underlords',
          name: 'Dota Underlords',
          added: 3784,
        },
        {
          id: 2055,
          slug: 'adventure-capitalist',
          name: 'AdVenture Capitalist',
          added: 3166,
        },
        {
          id: 758,
          slug: 'hue',
          name: 'Hue',
          added: 2151,
        },
        {
          id: 2306,
          slug: 'poker-night-2',
          name: 'Poker Night 2',
          added: 1985,
        },
        {
          id: 3187,
          slug: 'armello',
          name: 'Armello',
          added: 1909,
        },
      ],
    },
    {
      id: 34,
      name: 'Educational',
      slug: 'educational',
      games_count: 15650,
      image_background:
        'https://media.rawg.io/media/screenshots/312/3123c2b86ff947d3b6a846c771817e06.jpeg',
      games: [
        {
          id: 1358,
          slug: 'papers-please',
          name: 'Papers, Please',
          added: 6427,
        },
        {
          id: 1140,
          slug: 'world-of-goo',
          name: 'World of Goo',
          added: 4222,
        },
        {
          id: 2778,
          slug: 'surgeon-simulator-cpr',
          name: 'Surgeon Simulator',
          added: 3734,
        },
        {
          id: 9768,
          slug: 'gameguru',
          name: 'GameGuru',
          added: 2407,
        },
        {
          id: 13777,
          slug: 'sid-meiers-civilization-iv-colonization',
          name: "Sid Meier's Civilization IV: Colonization",
          added: 2201,
        },
        {
          id: 6885,
          slug: 'pirates-3',
          name: "Sid Meier's Pirates!",
          added: 2119,
        },
      ],
    },
    {
      id: 17,
      name: 'Card',
      slug: 'card',
      games_count: 4508,
      image_background:
        'https://media.rawg.io/media/screenshots/3f5/3f58a7b2a2b290994eb798eb72ca3fb2.jpg',
      games: [
        {
          id: 23557,
          slug: 'gwent-the-witcher-card-game',
          name: 'Gwent: The Witcher Card Game',
          added: 4496,
        },
        {
          id: 28121,
          slug: 'slay-the-spire',
          name: 'Slay the Spire',
          added: 4498,
        },
        {
          id: 18852,
          slug: 'poker-night-at-the-inventory',
          name: 'Poker Night at the Inventory',
          added: 2645,
        },
        {
          id: 8923,
          slug: 'faeria',
          name: 'Faeria',
          added: 2070,
        },
        {
          id: 332,
          slug: 'the-elder-scrolls-legends',
          name: 'The Elder Scrolls: Legends',
          added: 2035,
        },
        {
          id: 2306,
          slug: 'poker-night-2',
          name: 'Poker Night 2',
          added: 1985,
        },
      ],
    },
  ],
};

export const platforms = {
  count: 14,
  next: null,
  previous: null,
  results: [
    {
      id: 1,
      name: 'PC',
      slug: 'pc',
      platforms: [
        {
          id: 4,
          name: 'PC',
          slug: 'pc',
          games_count: 516132,
          image_background:
            'https://media.rawg.io/media/games/7fa/7fa0b586293c5861ee32490e953a4996.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 2,
      name: 'PlayStation',
      slug: 'playstation',
      platforms: [
        {
          id: 187,
          name: 'PlayStation 5',
          slug: 'playstation5',
          games_count: 931,
          image_background:
            'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg',
          image: null,
          year_start: 2020,
          year_end: null,
        },
        {
          id: 18,
          name: 'PlayStation 4',
          slug: 'playstation4',
          games_count: 6701,
          image_background:
            'https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 16,
          name: 'PlayStation 3',
          slug: 'playstation3',
          games_count: 3170,
          image_background:
            'https://media.rawg.io/media/games/2ba/2bac0e87cf45e5b508f227d281c9252a.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 15,
          name: 'PlayStation 2',
          slug: 'playstation2',
          games_count: 1988,
          image_background:
            'https://media.rawg.io/media/games/dd7/dd72d8a527cd9245c7eb7cd05aa53efa.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 27,
          name: 'PlayStation',
          slug: 'playstation1',
          games_count: 1631,
          image_background:
            'https://media.rawg.io/media/games/8fc/8fcc2ff5c7bcdb58199b1a4326817ceb.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 19,
          name: 'PS Vita',
          slug: 'ps-vita',
          games_count: 1453,
          image_background:
            'https://media.rawg.io/media/games/2f5/2f5eb72fe45540e93ac2726877551a20.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 17,
          name: 'PSP',
          slug: 'psp',
          games_count: 1367,
          image_background:
            'https://media.rawg.io/media/screenshots/55f/55f3e8983c17a0ef9e6b18aedd4f6794.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 3,
      name: 'Xbox',
      slug: 'xbox',
      platforms: [
        {
          id: 1,
          name: 'Xbox One',
          slug: 'xbox-one',
          games_count: 5538,
          image_background:
            'https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 186,
          name: 'Xbox Series S/X',
          slug: 'xbox-series-x',
          games_count: 798,
          image_background:
            'https://media.rawg.io/media/games/786/7863e587bac630de82fca50d799236a9.jpg',
          image: null,
          year_start: 2020,
          year_end: null,
        },
        {
          id: 14,
          name: 'Xbox 360',
          slug: 'xbox360',
          games_count: 2785,
          image_background:
            'https://media.rawg.io/media/games/021/021c4e21a1824d2526f925eff6324653.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 80,
          name: 'Xbox',
          slug: 'xbox-old',
          games_count: 725,
          image_background:
            'https://media.rawg.io/media/games/2ee/2eef5ed5e82c28d1299ecc2a0e60f2cb.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 4,
      name: 'iOS',
      slug: 'ios',
      platforms: [
        {
          id: 3,
          name: 'iOS',
          slug: 'ios',
          games_count: 77063,
          image_background:
            'https://media.rawg.io/media/games/daa/daaee07fcb40744d90cf8142f94a241f.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 8,
      name: 'Android',
      slug: 'android',
      platforms: [
        {
          id: 21,
          name: 'Android',
          slug: 'android',
          games_count: 52263,
          image_background:
            'https://media.rawg.io/media/games/5fa/5fae5fec3c943179e09da67a4427d68f.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 5,
      name: 'Apple Macintosh',
      slug: 'mac',
      platforms: [
        {
          id: 5,
          name: 'macOS',
          slug: 'macos',
          games_count: 101953,
          image_background:
            'https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 55,
          name: 'Classic Macintosh',
          slug: 'macintosh',
          games_count: 676,
          image_background:
            'https://media.rawg.io/media/games/104/104e82a52297cc7ddd3b05b7e68be04f.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 41,
          name: 'Apple II',
          slug: 'apple-ii',
          games_count: 423,
          image_background:
            'https://media.rawg.io/media/screenshots/4da/4dadb6e7a52030a3e530b665ecc7fd30.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 6,
      name: 'Linux',
      slug: 'linux',
      platforms: [
        {
          id: 6,
          name: 'Linux',
          slug: 'linux',
          games_count: 75440,
          image_background:
            'https://media.rawg.io/media/games/73e/73eecb8909e0c39fb246f457b5d6cbbe.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 7,
      name: 'Nintendo',
      slug: 'nintendo',
      platforms: [
        {
          id: 7,
          name: 'Nintendo Switch',
          slug: 'nintendo-switch',
          games_count: 5305,
          image_background:
            'https://media.rawg.io/media/games/f99/f9979698c43fd84c3ab69280576dd3af.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 8,
          name: 'Nintendo 3DS',
          slug: 'nintendo-3ds',
          games_count: 1701,
          image_background:
            'https://media.rawg.io/media/screenshots/a5a/a5a8e5820043aa1285643f3d243e5664.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 9,
          name: 'Nintendo DS',
          slug: 'nintendo-ds',
          games_count: 2478,
          image_background:
            'https://media.rawg.io/media/screenshots/4d5/4d558909512d99baeca227b50ff34595.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 13,
          name: 'Nintendo DSi',
          slug: 'nintendo-dsi',
          games_count: 37,
          image_background:
            'https://media.rawg.io/media/screenshots/b45/b452e9b20e969a64d0088ae467d1dcab.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 10,
          name: 'Wii U',
          slug: 'wii-u',
          games_count: 1146,
          image_background:
            'https://media.rawg.io/media/games/6c8/6c8cb4780ce30b76b944cf656e8fff49.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 11,
          name: 'Wii',
          slug: 'wii',
          games_count: 2248,
          image_background:
            'https://media.rawg.io/media/screenshots/157/1571cdfb52888191eabaf53c2b897240.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 105,
          name: 'GameCube',
          slug: 'gamecube',
          games_count: 635,
          image_background:
            'https://media.rawg.io/media/games/fee/fee0100afd87b52bfbd33e26689fa26c.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 83,
          name: 'Nintendo 64',
          slug: 'nintendo-64',
          games_count: 363,
          image_background:
            'https://media.rawg.io/media/games/0c5/0c5fcdf04048200da14b90e0e6cfaf6b.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 24,
          name: 'Game Boy Advance',
          slug: 'game-boy-advance',
          games_count: 950,
          image_background:
            'https://media.rawg.io/media/games/621/621abeb341a359cf755be4f80fa09c7f.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 43,
          name: 'Game Boy Color',
          slug: 'game-boy-color',
          games_count: 413,
          image_background:
            'https://media.rawg.io/media/games/28b/28b088364ecab7870dffc3b710104734.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 26,
          name: 'Game Boy',
          slug: 'game-boy',
          games_count: 607,
          image_background:
            'https://media.rawg.io/media/games/e40/e4043e92866d08ec9fdd212dcd3a1224.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 79,
          name: 'SNES',
          slug: 'snes',
          games_count: 949,
          image_background:
            'https://media.rawg.io/media/games/ae4/ae404f4e0f504131199703c09111bb78.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 49,
          name: 'NES',
          slug: 'nes',
          games_count: 980,
          image_background:
            'https://media.rawg.io/media/games/583/583615a299e4f355dfac6acebb95f2a9.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 9,
      name: 'Atari',
      slug: 'atari',
      platforms: [
        {
          id: 28,
          name: 'Atari 7800',
          slug: 'atari-7800',
          games_count: 64,
          image_background:
            'https://media.rawg.io/media/screenshots/565/56504b28b184dbc630a7de118e39d822.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 31,
          name: 'Atari 5200',
          slug: 'atari-5200',
          games_count: 64,
          image_background:
            'https://media.rawg.io/media/screenshots/61a/61a60e3ee55941387681eaa59e3becbf.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 23,
          name: 'Atari 2600',
          slug: 'atari-2600',
          games_count: 286,
          image_background:
            'https://media.rawg.io/media/screenshots/b12/b12ed274eed80e4aced37badf228d1cf.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 22,
          name: 'Atari Flashback',
          slug: 'atari-flashback',
          games_count: 30,
          image_background:
            'https://media.rawg.io/media/screenshots/2aa/2aa07f58491e14b0183333f8956bc802.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 25,
          name: 'Atari 8-bit',
          slug: 'atari-8-bit',
          games_count: 307,
          image_background:
            'https://media.rawg.io/media/screenshots/bb2/bb2cc339e686d70604d03659f6022381.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 34,
          name: 'Atari ST',
          slug: 'atari-st',
          games_count: 836,
          image_background:
            'https://media.rawg.io/media/games/3a0/3a015b41b9614b8649f22eeedb7c3454.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 46,
          name: 'Atari Lynx',
          slug: 'atari-lynx',
          games_count: 56,
          image_background:
            'https://media.rawg.io/media/screenshots/575/575b2838392ed177dd7d2c734c682f93.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 50,
          name: 'Atari XEGS',
          slug: 'atari-xegs',
          games_count: 22,
          image_background:
            'https://media.rawg.io/media/screenshots/769/7691726d70c23c029903df08858df001.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 112,
          name: 'Jaguar',
          slug: 'jaguar',
          games_count: 37,
          image_background:
            'https://media.rawg.io/media/games/855/8552687245f888ba388bc6ec0dcc3947.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 10,
      name: 'Commodore / Amiga',
      slug: 'commodore-amiga',
      platforms: [
        {
          id: 166,
          name: 'Commodore / Amiga',
          slug: 'commodore-amiga',
          games_count: 2077,
          image_background:
            'https://media.rawg.io/media/screenshots/5d8/5d89e3ef78840103848e59d631cfc431.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 11,
      name: 'SEGA',
      slug: 'sega',
      platforms: [
        {
          id: 167,
          name: 'Genesis',
          slug: 'genesis',
          games_count: 828,
          image_background:
            'https://media.rawg.io/media/games/637/637d7dc2f44d0f6ddd3ee2c0b1366962.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 107,
          name: 'SEGA Saturn',
          slug: 'sega-saturn',
          games_count: 357,
          image_background:
            'https://media.rawg.io/media/screenshots/681/68145c58e234705ed4559a05c043f41a.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 119,
          name: 'SEGA CD',
          slug: 'sega-cd',
          games_count: 160,
          image_background:
            'https://media.rawg.io/media/screenshots/364/364cb96fad83ff293e6359394a7cc51b.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 117,
          name: 'SEGA 32X',
          slug: 'sega-32x',
          games_count: 46,
          image_background:
            'https://media.rawg.io/media/screenshots/d9f/d9f308b5d824ae8f047edc0a998a587b.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 74,
          name: 'SEGA Master System',
          slug: 'sega-master-system',
          games_count: 225,
          image_background:
            'https://media.rawg.io/media/screenshots/cbc/cbca22c381d18a8df6e9361a33f8a899.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 106,
          name: 'Dreamcast',
          slug: 'dreamcast',
          games_count: 357,
          image_background:
            'https://media.rawg.io/media/screenshots/6e4/6e45a8e19beb5d510813f10f8af4eedc.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
        {
          id: 77,
          name: 'Game Gear',
          slug: 'game-gear',
          games_count: 218,
          image_background:
            'https://media.rawg.io/media/games/470/47058af09b864c2d211a08271eccfb4f.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 12,
      name: '3DO',
      slug: '3do',
      platforms: [
        {
          id: 111,
          name: '3DO',
          slug: '3do',
          games_count: 97,
          image_background:
            'https://media.rawg.io/media/screenshots/d8c/d8c399c09701ae2603043a3bb3a0bff5.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 13,
      name: 'Neo Geo',
      slug: 'neo-geo',
      platforms: [
        {
          id: 12,
          name: 'Neo Geo',
          slug: 'neogeo',
          games_count: 117,
          image_background:
            'https://media.rawg.io/media/screenshots/c5c/c5c2eb93a958dcb370db6a51a5bc84a3.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
    {
      id: 14,
      name: 'Web',
      slug: 'web',
      platforms: [
        {
          id: 171,
          name: 'Web',
          slug: 'web',
          games_count: 260091,
          image_background:
            'https://media.rawg.io/media/screenshots/2f2/2f2bca9ccd1d666e14f9f0554c42fb80.jpg',
          image: null,
          year_start: null,
          year_end: null,
        },
      ],
    },
  ],
};
